name: workshop-user-image
# This is the standard conda configuration file. Use this file to list
# the conda packages that you need installed in your environment.
channels:
  - conda-forge

dependencies:
  # data science
  - huggingface_hub==1.4.1
  - llama-cpp-python==0.3.16
  - openpyxl==3.1.5

  # AI/ML
  - pytorch==2.5.1

  # pip installed packages, conda is preferred
  - pip:
    # AI/ML
    - gpt4all==2.8.2
    - openai==2.31.0
    - gradio==5.49.1
    - anthropic==0.83.0
    - python-dotenv==1.2.1
    - jupyter-ai[all]==3.0.0
    - jupyter-ai-magics==2.31.7
    - transformers==5.2.0
    - langchain==0.3.27

    - stop-words==2025.11.4
    - google-genai==1.60.0
    - polars[all]==1.39.0
